package com.maple.dms.mappers;

import java.util.List;

import com.maple.dms.models.AccidentModel;

public interface AccidentModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int insert(AccidentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int insertSelective(AccidentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    AccidentModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int updateByPrimaryKeySelective(AccidentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int updateByPrimaryKey(AccidentModel record);
    
    // --------------- Below is customized -----------
    AccidentModel selectByDriverId(Long driverId);
    
    List<AccidentModel> selectAll();
}