package com.maple.dms.mappers;

import java.util.List;

import com.maple.dms.models.ChargeModel;

public interface ChargeModelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge
     *
     * @mbg.generated Wed Nov 15 19:51:28 CST 2017
     */
    int insert(ChargeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge
     *
     * @mbg.generated Wed Nov 15 19:51:28 CST 2017
     */
    int insertSelective(ChargeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge
     *
     * @mbg.generated Wed Nov 15 19:51:28 CST 2017
     */
    int updateByPrimaryKeySelective(ChargeModel record);
    
    /*
     * Below is customized
     */
    int deleteByPrimaryKey(Long id);
    
    ChargeModel selectByPrimaryKey(Long id);
    
    List<ChargeModel> selectAll();
}