package com.maple.dms.mappers;

import com.maple.dms.models.CivilDisputeModel;

public interface CivilDisputeModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table civil_dispute
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table civil_dispute
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int insert(CivilDisputeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table civil_dispute
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int insertSelective(CivilDisputeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table civil_dispute
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    CivilDisputeModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table civil_dispute
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int updateByPrimaryKeySelective(CivilDisputeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table civil_dispute
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int updateByPrimaryKey(CivilDisputeModel record);
    
    // --------------- Below is customized -----------
    CivilDisputeModel selectByDriverId(Long driverId);
}