package com.maple.dms.mappers;

import com.maple.dms.models.CodetableModel;

public interface CodetableModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int insert(CodetableModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int insertSelective(CodetableModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    CodetableModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int updateByPrimaryKeySelective(CodetableModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int updateByPrimaryKey(CodetableModel record);
}