package com.maple.dms.mappers;

import com.maple.dms.models.ComplaintModel;

public interface ComplaintModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int insert(ComplaintModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int insertSelective(ComplaintModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    ComplaintModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int updateByPrimaryKeySelective(ComplaintModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int updateByPrimaryKey(ComplaintModel record);

    // --------------- Below is customized -----------
    ComplaintModel selectByDriverId(Long driverId);
}