package com.maple.dms.mappers;

import com.maple.dms.models.ContractModel;

public interface ContractModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int insert(ContractModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int insertSelective(ContractModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    ContractModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int updateByPrimaryKeySelective(ContractModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int updateByPrimaryKey(ContractModel record);
    
    // --------------- Below is customized -----------
    ContractModel selectByDriverId(Long driverId);    
}