package com.maple.dms.mappers;

import java.util.List;

import com.maple.dms.models.DriverModel;

public interface DriverModelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int insert(DriverModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int insertSelective(DriverModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    DriverModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int updateByPrimaryKeySelective(DriverModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int updateByPrimaryKey(DriverModel record);
    
    // ------------ Below is customized -------------
    List<DriverModel> selectAllBase();
    
    int deleteByPrimaryKey(Long id);
    
    DriverModel selectByIdNo(Long idNo);
}