package com.maple.dms.mappers;

import com.maple.dms.models.DriverDetailModel;

public interface DriverDetailModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_detail
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_detail
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int insert(DriverDetailModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_detail
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    int insertSelective(DriverDetailModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_detail
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    DriverDetailModel selectByPrimaryKey(Long id);

    // --------------- Below is customized -----------
    DriverDetailModel selectByDriverId(Long driverId);

    int updateByPrimaryKeySelective(DriverDetailModel record);

    int updateByPrimaryKey(DriverDetailModel record);
}