package com.maple.dms.mappers;

import com.maple.dms.models.DriverDetailModel;

public interface DriverDetailModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_detail
     *
     * @mbg.generated Thu Nov 02 15:41:45 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_detail
     *
     * @mbg.generated Thu Nov 02 15:41:45 CST 2017
     */
    int insert(DriverDetailModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_detail
     *
     * @mbg.generated Thu Nov 02 15:41:45 CST 2017
     */
    int insertSelective(DriverDetailModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_detail
     *
     * @mbg.generated Thu Nov 02 15:41:45 CST 2017
     */
    DriverDetailModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_detail
     *
     * @mbg.generated Thu Nov 02 15:41:45 CST 2017
     */
    int updateByPrimaryKeySelective(DriverDetailModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_detail
     *
     * @mbg.generated Thu Nov 02 15:41:45 CST 2017
     */
    int updateByPrimaryKey(DriverDetailModel record);
    
    // ------ Customized -------------------------
    
    DriverDetailModel selectByDriverId(Long driverId);
}