package com.maple.dms.mappers;

import com.maple.dms.models.InsuranceModel;

public interface InsuranceModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int insert(InsuranceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int insertSelective(InsuranceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    InsuranceModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int updateByPrimaryKeySelective(InsuranceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    int updateByPrimaryKey(InsuranceModel record);
    
    // --------------- Below is customized -----------
    InsuranceModel selectByDriverId(Long driverId);
}