package com.maple.dms.mappers;

import com.maple.dms.models.SubstituteDriverModel;

public interface SubstituteDriverModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substitute_driver
     *
     * @mbg.generated Thu Dec 14 22:31:30 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substitute_driver
     *
     * @mbg.generated Thu Dec 14 22:31:30 CST 2017
     */
    int insert(SubstituteDriverModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substitute_driver
     *
     * @mbg.generated Thu Dec 14 22:31:30 CST 2017
     */
    int insertSelective(SubstituteDriverModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substitute_driver
     *
     * @mbg.generated Thu Dec 14 22:31:30 CST 2017
     */
    SubstituteDriverModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substitute_driver
     *
     * @mbg.generated Thu Dec 14 22:31:30 CST 2017
     */
    int updateByPrimaryKeySelective(SubstituteDriverModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table substitute_driver
     *
     * @mbg.generated Thu Dec 14 22:31:30 CST 2017
     */
    int updateByPrimaryKey(SubstituteDriverModel record);
    
    // -------------------------
    SubstituteDriverModel selectByDriverId(Long driverId);
}