package com.maple.dms.models;

import java.util.Date;

public class AccidentModel {
	
	private String driverIdNo;
	
	private String driverName;
	
    public String getDriverIdNo() {
		return driverIdNo;
	}

	public void setDriverIdNo(String driverIdNo) {
		this.driverIdNo = driverIdNo;
	}

	public String getDriverName() {
		return driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date occurDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.responsibility_type_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long responsibilityTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.is_insurance_paid
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Boolean isInsurancePaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date lastUpdateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.is_active
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.id
     *
     * @return the value of accident.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.id
     *
     * @param id the value for accident.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.driver_id
     *
     * @return the value of accident.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.driver_id
     *
     * @param driverId the value for accident.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setDriverId(Long driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.occur_dt
     *
     * @return the value of accident.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getOccurDt() {
        return occurDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.occur_dt
     *
     * @param occurDt the value for accident.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setOccurDt(Date occurDt) {
        this.occurDt = occurDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.responsibility_type_id
     *
     * @return the value of accident.responsibility_type_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getResponsibilityTypeId() {
        return responsibilityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.responsibility_type_id
     *
     * @param responsibilityTypeId the value for accident.responsibility_type_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setResponsibilityTypeId(Long responsibilityTypeId) {
        this.responsibilityTypeId = responsibilityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.is_insurance_paid
     *
     * @return the value of accident.is_insurance_paid
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Boolean getIsInsurancePaid() {
        return isInsurancePaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.is_insurance_paid
     *
     * @param isInsurancePaid the value for accident.is_insurance_paid
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setIsInsurancePaid(Boolean isInsurancePaid) {
        this.isInsurancePaid = isInsurancePaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.create_dt
     *
     * @return the value of accident.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.create_dt
     *
     * @param createDt the value for accident.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.last_update_dt
     *
     * @return the value of accident.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.last_update_dt
     *
     * @param lastUpdateDt the value for accident.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.is_active
     *
     * @return the value of accident.is_active
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.is_active
     *
     * @param isActive the value for accident.is_active
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
}