package com.maple.dms.models;

import java.util.Date;

public class CivilDisputeModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column civil_dispute.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column civil_dispute.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column civil_dispute.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date occurDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column civil_dispute.content
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column civil_dispute.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column civil_dispute.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date lastUpdateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column civil_dispute.is_active
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column civil_dispute.id
     *
     * @return the value of civil_dispute.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column civil_dispute.id
     *
     * @param id the value for civil_dispute.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column civil_dispute.driver_id
     *
     * @return the value of civil_dispute.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column civil_dispute.driver_id
     *
     * @param driverId the value for civil_dispute.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setDriverId(Long driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column civil_dispute.occur_dt
     *
     * @return the value of civil_dispute.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getOccurDt() {
        return occurDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column civil_dispute.occur_dt
     *
     * @param occurDt the value for civil_dispute.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setOccurDt(Date occurDt) {
        this.occurDt = occurDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column civil_dispute.content
     *
     * @return the value of civil_dispute.content
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column civil_dispute.content
     *
     * @param content the value for civil_dispute.content
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column civil_dispute.create_dt
     *
     * @return the value of civil_dispute.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column civil_dispute.create_dt
     *
     * @param createDt the value for civil_dispute.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column civil_dispute.last_update_dt
     *
     * @return the value of civil_dispute.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column civil_dispute.last_update_dt
     *
     * @param lastUpdateDt the value for civil_dispute.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column civil_dispute.is_active
     *
     * @return the value of civil_dispute.is_active
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column civil_dispute.is_active
     *
     * @param isActive the value for civil_dispute.is_active
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
}