package com.maple.dms.models;

public class CodetableModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codetable.id
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codetable.category
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codetable.name
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codetable.display_value
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    private String displayValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codetable.is_active
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codetable.id
     *
     * @return the value of codetable.id
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codetable.id
     *
     * @param id the value for codetable.id
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codetable.category
     *
     * @return the value of codetable.category
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codetable.category
     *
     * @param category the value for codetable.category
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codetable.name
     *
     * @return the value of codetable.name
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codetable.name
     *
     * @param name the value for codetable.name
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codetable.display_value
     *
     * @return the value of codetable.display_value
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    public String getDisplayValue() {
        return displayValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codetable.display_value
     *
     * @param displayValue the value for codetable.display_value
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    public void setDisplayValue(String displayValue) {
        this.displayValue = displayValue == null ? null : displayValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codetable.is_active
     *
     * @return the value of codetable.is_active
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codetable.is_active
     *
     * @param isActive the value for codetable.is_active
     *
     * @mbg.generated Tue Oct 24 17:12:44 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
}