package com.maple.dms.models;

import java.util.Date;

public class ComplaintModel {
	
	private String carNumber;
	
	public String getCarNumber() {
		return carNumber;
	}

	public void setCarNumber(String carNumber) {
		this.carNumber = carNumber;
	}

	
	private String driverName;
	
	private String driverIdNo;
	
	public String getDriverName() {
		return driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	public String getDriverIdNo() {
		return driverIdNo;
	}

	public void setDriverIdNo(String driverIdNo) {
		this.driverIdNo = driverIdNo;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date occurDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.content
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.is_solved
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Boolean isSolved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.solve_way
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private String solveWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date lastUpdateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.is_active
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.id
     *
     * @return the value of complaint.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.id
     *
     * @param id the value for complaint.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.driver_id
     *
     * @return the value of complaint.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.driver_id
     *
     * @param driverId the value for complaint.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setDriverId(Long driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.occur_dt
     *
     * @return the value of complaint.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getOccurDt() {
        return occurDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.occur_dt
     *
     * @param occurDt the value for complaint.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setOccurDt(Date occurDt) {
        this.occurDt = occurDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.content
     *
     * @return the value of complaint.content
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.content
     *
     * @param content the value for complaint.content
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.is_solved
     *
     * @return the value of complaint.is_solved
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Boolean getIsSolved() {
        return isSolved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.is_solved
     *
     * @param isSolved the value for complaint.is_solved
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setIsSolved(Boolean isSolved) {
        this.isSolved = isSolved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.solve_way
     *
     * @return the value of complaint.solve_way
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public String getSolveWay() {
        return solveWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.solve_way
     *
     * @param solveWay the value for complaint.solve_way
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setSolveWay(String solveWay) {
        this.solveWay = solveWay == null ? null : solveWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.create_dt
     *
     * @return the value of complaint.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.create_dt
     *
     * @param createDt the value for complaint.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.last_update_dt
     *
     * @return the value of complaint.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.last_update_dt
     *
     * @param lastUpdateDt the value for complaint.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.is_active
     *
     * @return the value of complaint.is_active
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.is_active
     *
     * @param isActive the value for complaint.is_active
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
}