package com.maple.dms.models;

import java.util.Date;

public class ContractModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.photo_path
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private String photoPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.start_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date startDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.end_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date endDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.supplementary
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private String supplementary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.id
     *
     * @return the value of contract.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.id
     *
     * @param id the value for contract.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.driver_id
     *
     * @return the value of contract.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.driver_id
     *
     * @param driverId the value for contract.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setDriverId(Long driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.photo_path
     *
     * @return the value of contract.photo_path
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.photo_path
     *
     * @param photoPath the value for contract.photo_path
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath == null ? null : photoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.start_dt
     *
     * @return the value of contract.start_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getStartDt() {
        return startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.start_dt
     *
     * @param startDt the value for contract.start_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setStartDt(Date startDt) {
        this.startDt = startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.end_dt
     *
     * @return the value of contract.end_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getEndDt() {
        return endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.end_dt
     *
     * @param endDt the value for contract.end_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.supplementary
     *
     * @return the value of contract.supplementary
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public String getSupplementary() {
        return supplementary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.supplementary
     *
     * @param supplementary the value for contract.supplementary
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setSupplementary(String supplementary) {
        this.supplementary = supplementary == null ? null : supplementary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.create_dt
     *
     * @return the value of contract.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.create_dt
     *
     * @param createDt the value for contract.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.last_update_dt
     *
     * @return the value of contract.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.last_update_dt
     *
     * @param lastUpdateDt the value for contract.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}