package com.maple.dms.models;

import java.util.Date;

public class DriverModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.id_no
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private String idNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.name
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.address
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.phonenumber
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driving_license_path
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private String drivingLicensePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.vehicle_travel_license_path
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private String vehicleTravelLicensePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.certificate_path
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private String certificatePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.certificate_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Date certificateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.create_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Date lastUpdateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.is_active
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.id
     *
     * @return the value of driver.id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.id
     *
     * @param id the value for driver.id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.id_no
     *
     * @return the value of driver.id_no
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.id_no
     *
     * @param idNo the value for driver.id_no
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.name
     *
     * @return the value of driver.name
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.name
     *
     * @param name the value for driver.name
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.address
     *
     * @return the value of driver.address
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.address
     *
     * @param address the value for driver.address
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.phonenumber
     *
     * @return the value of driver.phonenumber
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.phonenumber
     *
     * @param phonenumber the value for driver.phonenumber
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driving_license_path
     *
     * @return the value of driver.driving_license_path
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public String getDrivingLicensePath() {
        return drivingLicensePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driving_license_path
     *
     * @param drivingLicensePath the value for driver.driving_license_path
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setDrivingLicensePath(String drivingLicensePath) {
        this.drivingLicensePath = drivingLicensePath == null ? null : drivingLicensePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.vehicle_travel_license_path
     *
     * @return the value of driver.vehicle_travel_license_path
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public String getVehicleTravelLicensePath() {
        return vehicleTravelLicensePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.vehicle_travel_license_path
     *
     * @param vehicleTravelLicensePath the value for driver.vehicle_travel_license_path
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setVehicleTravelLicensePath(String vehicleTravelLicensePath) {
        this.vehicleTravelLicensePath = vehicleTravelLicensePath == null ? null : vehicleTravelLicensePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.certificate_path
     *
     * @return the value of driver.certificate_path
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public String getCertificatePath() {
        return certificatePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.certificate_path
     *
     * @param certificatePath the value for driver.certificate_path
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setCertificatePath(String certificatePath) {
        this.certificatePath = certificatePath == null ? null : certificatePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.certificate_dt
     *
     * @return the value of driver.certificate_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Date getCertificateDt() {
        return certificateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.certificate_dt
     *
     * @param certificateDt the value for driver.certificate_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setCertificateDt(Date certificateDt) {
        this.certificateDt = certificateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.create_dt
     *
     * @return the value of driver.create_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.create_dt
     *
     * @param createDt the value for driver.create_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.last_update_dt
     *
     * @return the value of driver.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.last_update_dt
     *
     * @param lastUpdateDt the value for driver.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.is_active
     *
     * @return the value of driver.is_active
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.is_active
     *
     * @param isActive the value for driver.is_active
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    
    // -------------------- Below is customized ----------------
    private DriverDetailModel driverDetailModel;

	public DriverDetailModel getDriverDetailModel() {
		return driverDetailModel;
	}

	public void setDriverDetailModel(DriverDetailModel driverDetailModel) {
		this.driverDetailModel = driverDetailModel;
	}
    
}