package com.maple.dms.models;

import java.util.Date;

public class DriverDetailModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.driver_id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Long driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.vehicle_operating_id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private String vehicleOperatingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.vehicle_registration
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private String vehicleRegistration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.annual_audit
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Date annualAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.substitute_driver_id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Long substituteDriverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.change_car_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Date changeCarDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.change_car_fee
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Double changeCarFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.is_transfer_ownership
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Boolean isTransferOwnership;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.create_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_detail.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.id
     *
     * @return the value of driver_detail.id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.id
     *
     * @param id the value for driver_detail.id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.driver_id
     *
     * @return the value of driver_detail.driver_id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Long getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.driver_id
     *
     * @param driverId the value for driver_detail.driver_id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setDriverId(Long driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.vehicle_operating_id
     *
     * @return the value of driver_detail.vehicle_operating_id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public String getVehicleOperatingId() {
        return vehicleOperatingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.vehicle_operating_id
     *
     * @param vehicleOperatingId the value for driver_detail.vehicle_operating_id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setVehicleOperatingId(String vehicleOperatingId) {
        this.vehicleOperatingId = vehicleOperatingId == null ? null : vehicleOperatingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.vehicle_registration
     *
     * @return the value of driver_detail.vehicle_registration
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public String getVehicleRegistration() {
        return vehicleRegistration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.vehicle_registration
     *
     * @param vehicleRegistration the value for driver_detail.vehicle_registration
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setVehicleRegistration(String vehicleRegistration) {
        this.vehicleRegistration = vehicleRegistration == null ? null : vehicleRegistration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.annual_audit
     *
     * @return the value of driver_detail.annual_audit
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Date getAnnualAudit() {
        return annualAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.annual_audit
     *
     * @param annualAudit the value for driver_detail.annual_audit
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setAnnualAudit(Date annualAudit) {
        this.annualAudit = annualAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.substitute_driver_id
     *
     * @return the value of driver_detail.substitute_driver_id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Long getSubstituteDriverId() {
        return substituteDriverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.substitute_driver_id
     *
     * @param substituteDriverId the value for driver_detail.substitute_driver_id
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setSubstituteDriverId(Long substituteDriverId) {
        this.substituteDriverId = substituteDriverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.change_car_dt
     *
     * @return the value of driver_detail.change_car_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Date getChangeCarDt() {
        return changeCarDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.change_car_dt
     *
     * @param changeCarDt the value for driver_detail.change_car_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setChangeCarDt(Date changeCarDt) {
        this.changeCarDt = changeCarDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.change_car_fee
     *
     * @return the value of driver_detail.change_car_fee
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Double getChangeCarFee() {
        return changeCarFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.change_car_fee
     *
     * @param changeCarFee the value for driver_detail.change_car_fee
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setChangeCarFee(Double changeCarFee) {
        this.changeCarFee = changeCarFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.is_transfer_ownership
     *
     * @return the value of driver_detail.is_transfer_ownership
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Boolean getIsTransferOwnership() {
        return isTransferOwnership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.is_transfer_ownership
     *
     * @param isTransferOwnership the value for driver_detail.is_transfer_ownership
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setIsTransferOwnership(Boolean isTransferOwnership) {
        this.isTransferOwnership = isTransferOwnership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.create_dt
     *
     * @return the value of driver_detail.create_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.create_dt
     *
     * @param createDt the value for driver_detail.create_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_detail.last_update_dt
     *
     * @return the value of driver_detail.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_detail.last_update_dt
     *
     * @param lastUpdateDt the value for driver_detail.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:12:45 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}