package com.maple.dms.models;

import java.util.Date;

public class InsuranceModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Long driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.photo_path
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private String photoPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date occurDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.premium
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Double premium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.insured_company
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private String insuredCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.id
     *
     * @return the value of insurance.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.id
     *
     * @param id the value for insurance.id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.driver_id
     *
     * @return the value of insurance.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Long getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.driver_id
     *
     * @param driverId the value for insurance.driver_id
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setDriverId(Long driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.photo_path
     *
     * @return the value of insurance.photo_path
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.photo_path
     *
     * @param photoPath the value for insurance.photo_path
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath == null ? null : photoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.occur_dt
     *
     * @return the value of insurance.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getOccurDt() {
        return occurDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.occur_dt
     *
     * @param occurDt the value for insurance.occur_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setOccurDt(Date occurDt) {
        this.occurDt = occurDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.premium
     *
     * @return the value of insurance.premium
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Double getPremium() {
        return premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.premium
     *
     * @param premium the value for insurance.premium
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setPremium(Double premium) {
        this.premium = premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.insured_company
     *
     * @return the value of insurance.insured_company
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public String getInsuredCompany() {
        return insuredCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.insured_company
     *
     * @param insuredCompany the value for insurance.insured_company
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setInsuredCompany(String insuredCompany) {
        this.insuredCompany = insuredCompany == null ? null : insuredCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.create_dt
     *
     * @return the value of insurance.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.create_dt
     *
     * @param createDt the value for insurance.create_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.last_update_dt
     *
     * @return the value of insurance.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.last_update_dt
     *
     * @param lastUpdateDt the value for insurance.last_update_dt
     *
     * @mbg.generated Tue Oct 24 17:43:16 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}